const COPY: Record<string, { displayName: string; running: string; completed: string }> = {
  'theta.dataset.request_upload': { displayName: '请求上传数据', running: 'Agent 正在请求你提供研究数据', completed: 'Agent 已发起数据上传请求' },
  'theta.dataset.ingest_attachment': { displayName: '摄取数据附件', running: '正在校验、托管并登记已上传的数据', completed: '已完成数据附件摄取' },
  'theta.dataset.overview': { displayName: '读取数据概况', running: '正在读取数据量和列名', completed: '已读取数据概况' },
  'theta.dataset.sample': { displayName: '查看脱敏样本', running: '正在查看最多 10 条已授权脱敏样本', completed: '已查看脱敏样本' },
  'theta.dataset.column_profile': { displayName: '分析列特征', running: '正在分析列类型和取值特征', completed: '已分析列特征' },
  'theta.dataset.text_profile': { displayName: '分析正文特征', running: '正在分析正文长度、稀疏性和重复情况', completed: '已分析正文特征' },
  'theta.dataset.time_profile': { displayName: '检查时间信息', running: '正在判断时间列是否适合分析', completed: '已检查时间信息' },
  'theta.dataset.categorical_profile': { displayName: '检查分类信息', running: '正在分析可用于比较的分类列', completed: '已检查分类信息' },
  'theta.dataset.missingness': { displayName: '检查缺失值', running: '正在检查各列缺失情况', completed: '已检查缺失值' },
  'theta.dataset.duplicates': { displayName: '检查重复数据', running: '正在检查重复记录和重复正文', completed: '已检查重复数据' },
  'theta.dataset.relationships': { displayName: '分析列关系', running: '正在分析正文、时间和分类列之间的关系', completed: '已分析列关系' },
  'theta.dataset.submit_understanding': { displayName: '整理数据理解', running: '正在形成有证据的数据理解', completed: '已形成数据理解' },
  'theta.dataset.apply_user_revision': { displayName: '修订数据理解', running: '正在根据你的反馈修订数据理解', completed: '已修订数据理解' },
  'theta.research.read_workspace': { displayName: '读取研究上下文', running: '正在回顾数据理解和已有研究意图', completed: '已读取研究上下文' },
  'theta.research.update_understanding': { displayName: '更新研究意图', running: '正在根据对话更新研究意图', completed: '已更新研究意图' },
  'theta.model.catalog': { displayName: '读取模型目录', running: '正在读取本地可用模型目录', completed: '已读取模型目录' },
  'theta.model.list_available': { displayName: '检查可用模型', running: '正在检查当前环境可执行的模型', completed: '已检查可用模型' },
  'theta.model.get_capability': { displayName: '读取模型能力', running: '正在读取模型能力和适用条件', completed: '已读取模型能力' },
  'theta.model.compare': { displayName: '比较候选模型', running: '正在比较候选模型与研究目标的匹配程度', completed: '已比较候选模型' },
  'theta.model.get_parameter_contract': { displayName: '读取参数约束', running: '正在读取模型超参数约束', completed: '已读取参数约束' },
  'theta.runtime.profile_hardware': { displayName: '检查运行环境', running: '正在读取 CPU、内存和可用运行资源', completed: '已检查运行环境' },
  'theta.runtime.check_dependencies': { displayName: '检查训练依赖', running: '正在检查训练所需依赖', completed: '已检查训练依赖' },
  'theta.runtime.check_model_assets': { displayName: '检查模型资源', running: '正在检查模型所需的本地资源', completed: '已检查模型资源' },
  'theta.runtime.check_offline_readiness': { displayName: '检查离线可用性', running: '正在确认离线训练条件', completed: '已检查离线可用性' },
  'theta.runtime.estimate_candidate': { displayName: '估算训练开销', running: '正在估算候选方案的训练开销', completed: '已估算训练开销' },
  'theta.planner.inspect_case': { displayName: '整理规划上下文', running: '正在汇总数据、研究目标、环境和当前候选', completed: '已整理规划上下文' },
  'theta.model.shortlist': { displayName: '筛选可用模型', running: '正在检查候选模型能力、参数和本地可用性', completed: '已完成候选模型筛选' },
  'theta.rag.search': { displayName: '检索研究证据', running: '正在本地知识库检索模型与实践证据', completed: '已检索研究证据' },
  'theta.rag.get_evidence': { displayName: '读取证据详情', running: '正在读取已检索证据的详情', completed: '已读取证据详情' },
  'theta.rag.find_conflicts': { displayName: '检查证据冲突', running: '正在检查模型建议之间的证据冲突', completed: '已检查证据冲突' },
  'theta.rag.compare_models': { displayName: '按证据比较模型', running: '正在使用本地证据比较候选模型', completed: '已完成证据比较' },
  'theta.rag.check_claim_support': { displayName: '核对方案依据', running: '正在核对计划主张是否有合法证据支持', completed: '已核对方案依据' },
  'theta.planner.create_candidate': { displayName: '创建候选计划', running: '正在把研究意图编译为候选计划', completed: '已创建候选计划' },
  'theta.planner.submit_revision': { displayName: '修订候选计划', running: '正在根据校验问题修订候选计划', completed: '已修订候选计划' },
  'theta.planner.evaluate_candidate': { displayName: '校验候选计划', running: '正在绑定证据并检查参数、环境和研究意图一致性', completed: '已完成候选计划校验' },
  'theta.planner.validate_alignment': { displayName: '检查意图一致性', running: '正在检查研究意图是否全部落实', completed: '已检查研究意图一致性' },
  'theta.planner.get_candidate': { displayName: '读取当前计划', running: '正在读取当前候选、证据和校验收据', completed: '已读取当前计划' },
  'theta.plan.create': { displayName: '生成可执行训练计划', running: '正在把已确认方案编译为唯一的可执行计划', completed: '已生成可执行训练计划' },
  'theta.training.dry_run': { displayName: '执行训练前检查', running: '正在检查数据、依赖、命令和预期产物', completed: '已完成训练前检查' },
  'theta.dataset.verify_for_training': { displayName: '复核训练数据', running: '正在复核数据哈希和列绑定', completed: '已复核训练数据' },
  'theta.training.start': { displayName: '启动训练', running: '正在启动已批准的训练任务', completed: '已启动训练任务' },
  'theta.training.status': { displayName: '读取训练状态', running: '正在读取训练任务的当前状态', completed: '已读取训练状态' },
  'theta.training.cancel': { displayName: '取消训练', running: '正在提交训练取消请求', completed: '已提交训练取消请求' },
  'theta.results.verify_artifacts': { displayName: '验证训练产物', running: '正在校验训练结果文件和哈希', completed: '已验证训练产物' },
  'theta.results.list_artifacts': { displayName: '列出训练产物', running: '正在读取可用训练结果文件', completed: '已读取训练产物列表' },
  'theta.results.get_summary': { displayName: '读取结果摘要', running: '正在读取已验证的训练结果摘要', completed: '已读取结果摘要' },
  'theta.agent.protocol_feedback': { displayName: '修正 Agent 协议', running: '正在修正不合法的阶段动作', completed: '已完成协议修正' },
};

export const toolActivityCopy = (toolId: string, fallbackName?: string): { displayName: string; running: string; completed: string; failed: string } => {
  const value = COPY[toolId] ?? {
    displayName: fallbackName ?? toolId,
    running: `正在调用 ${fallbackName ?? toolId}`,
    completed: `已完成 ${fallbackName ?? toolId}`,
  };
  return { ...value, failed: `${value.displayName}失败` };
};
