export const THETA_TOOL_IDS = {
  agentProtocolFeedback: 'theta.agent.protocol_feedback',
  datasetRequestUpload: 'theta.dataset.request_upload',
  datasetIngestAttachment: 'theta.dataset.ingest_attachment',
  datasetOverview: "theta.dataset.overview",
  datasetSample: "theta.dataset.sample",
  datasetColumnProfile: "theta.dataset.column_profile",
  datasetTextProfile: "theta.dataset.text_profile",
  datasetTimeProfile: "theta.dataset.time_profile",
  datasetCategoricalProfile: "theta.dataset.categorical_profile",
  datasetMissingness: "theta.dataset.missingness",
  datasetDuplicates: "theta.dataset.duplicates",
  datasetRelationships: "theta.dataset.relationships",
  datasetSubmitUnderstanding: "theta.dataset.submit_understanding",
  datasetApplyUserRevision: "theta.dataset.apply_user_revision",
  researchReadWorkspace: "theta.research.read_workspace",
  researchUpdateUnderstanding: "theta.research.update_understanding",
  modelCatalog: "theta.model.catalog",
  modelListAvailable: "theta.model.list_available",
  modelGetCapability: "theta.model.get_capability",
  modelCompare: "theta.model.compare",
  modelGetParameterContract: "theta.model.get_parameter_contract",
  runtimeProfileHardware: "theta.runtime.profile_hardware",
  runtimeCheckDependencies: "theta.runtime.check_dependencies",
  runtimeCheckModelAssets: "theta.runtime.check_model_assets",
  runtimeCheckOfflineReadiness: "theta.runtime.check_offline_readiness",
  runtimeEstimateCandidate: "theta.runtime.estimate_candidate",
  ragIndex: "theta.rag.index",
  ragStatus: "theta.rag.status",
  ragSearch: "theta.rag.search",
  ragGetEvidence: "theta.rag.get_evidence",
  ragFindConflicts: "theta.rag.find_conflicts",
  ragCompareModels: "theta.rag.compare_models",
  ragCheckClaimSupport: "theta.rag.check_claim_support",
  plannerCreateCandidate: "theta.planner.create_candidate",
  plannerGetCandidate: "theta.planner.get_candidate",
  plannerCompareCandidates: "theta.planner.compare_candidates",
  plannerSubmitRevision: "theta.planner.submit_revision",
  plannerEstimateProtocol: "theta.planner.estimate_protocol",
  plannerSelectEvidence: "theta.planner.select_evidence",
  plannerValidatePreview: "theta.planner.validate_preview",
  plannerInspectCase: "theta.planner.inspect_case",
  modelShortlist: "theta.model.shortlist",
  plannerEvaluateCandidate: "theta.planner.evaluate_candidate",
  plannerValidateAlignment: "theta.planner.validate_alignment",
  planCreate: "theta.plan.create",
  trainingDryRun: "theta.training.dry_run",
  datasetVerifyForTraining: 'theta.dataset.verify_for_training',
  trainingStart: 'theta.training.start',
  trainingStatus: 'theta.training.status',
  trainingCancel: 'theta.training.cancel',
  artifactsVerify: 'theta.results.verify_artifacts',
  resultsListArtifacts: 'theta.results.list_artifacts',
  resultsGetSummary: 'theta.results.get_summary',
} as const;

export type ThetaToolId = (typeof THETA_TOOL_IDS)[keyof typeof THETA_TOOL_IDS];

export const THETA_PERMISSION_SCOPES = {
  datasetRead: "theta:dataset:read",
  datasetWrite: "theta:dataset:write",
  researchRead: "theta:research:read",
  researchWrite: "theta:research:write",
  modelRead: "theta:model:read",
  planRead: "theta:plan:read",
  planWrite: "theta:plan:write",
  runtimeRead: "theta:runtime:read",
  ragRead: "theta:rag:read",
  ragWrite: "theta:rag:write",
  inferenceUse: "theta:inference:use",
  eventsRead: "theta:events:read",
  trainingRead: 'theta:training:read',
  trainingWrite: 'theta:training:write',
  resultsRead: 'theta:results:read',
} as const;
